version: "3.2"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 4003:4003
      - 4004:4004
    depends_on:
      - db
    networks:
      - mynetwork
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PORT=3307
      - DB_PASSWORD=password
      - DB_DATABASE=cost_estimator_db
    container_name: app-container

  db:
    image: mysql:latest
    ports:
      - 3307:3307
    networks:
      - mynetwork
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=cost_estimator_db
    container_name: db-container

networks:
  mynetwork:
    driver: bridge