version: "3.2"
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db
    image: my-web-app
    networks:
      - frontend
      - backend
    environment:
      - DB_HOST=docker-mysql
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_DATABASE=const_estimator_db
    container_name: portfolio-project
  db:
    image: mysql
    networks:
      - backend
    environment:
      - DB_HOST=docker-mysql
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_DATABASE=const_estimator_db
    container_name: portfolio-project
networks:
  frontend:
  backend: